repositories:
#  - name: generalmeow
#    url: https://charts.bitnami.com/bitnami

releases:
#  - name: nginx-example
#    namespace: default
#    chart: bitnami/nginx
#  - name: nginx-example-with-custom-values
#    namespace: default
#    chart: bitnami/nginx
#    values:
#      - nginx-custom-values/nginx-values.yaml

  - name: home-dashboard-fe                            # name of this release
    namespace: default                       # target namespace
    chart: ./charts/home-dashboard-fe              # the chart being installed to create this release, referenced by relative path to local helmfile
#    values:
#      - "../../my-values/grafana/values.yaml"             # Values file (relative path to manifest)
#      - ./values/{{ requiredEnv "PLATFORM_ENV" }}/config.yaml # Values file taken from path with environment variable. $PLATFORM_ENV must be set in the calling environment.
    wait: true